/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as CharactersIndexImport } from './routes/characters/index';
import { Route as CharactersCharactersIdImport } from './routes/characters/$charactersId';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const CharactersIndexRoute = CharactersIndexImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRoute,
} as any);

const CharactersCharactersIdRoute = CharactersCharactersIdImport.update({
  id: '/characters/$charactersId',
  path: '/characters/$charactersId',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/characters/$charactersId': {
      id: '/characters/$charactersId';
      path: '/characters/$charactersId';
      fullPath: '/characters/$charactersId';
      preLoaderRoute: typeof CharactersCharactersIdImport;
      parentRoute: typeof rootRoute;
    };
    '/characters/': {
      id: '/characters/';
      path: '/characters';
      fullPath: '/characters';
      preLoaderRoute: typeof CharactersIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/characters/$charactersId': typeof CharactersCharactersIdRoute;
  '/characters': typeof CharactersIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/characters/$charactersId': typeof CharactersCharactersIdRoute;
  '/characters': typeof CharactersIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/characters/$charactersId': typeof CharactersCharactersIdRoute;
  '/characters/': typeof CharactersIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/characters/$charactersId' | '/characters';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/characters/$charactersId' | '/characters';
  id: '__root__' | '/' | '/characters/$charactersId' | '/characters/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CharactersCharactersIdRoute: typeof CharactersCharactersIdRoute;
  CharactersIndexRoute: typeof CharactersIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersCharactersIdRoute: CharactersCharactersIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/characters/$charactersId",
        "/characters/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/characters/$charactersId": {
      "filePath": "characters/$charactersId.tsx"
    },
    "/characters/": {
      "filePath": "characters/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
